name: "Build & Deploy to Netlify"
on:
  pull_request:
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
    - name: Checking out the repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: true

    - uses: cachix/install-nix-action@v12
      with:
        install_url: https://github.com/numtide/nix-flakes-installer/releases/download/nix-2.4pre20210823_af94b54/install
        extra_nix_config:
          experimental-features = nix-command flakes

    - name: Building summer.nixos.org
      run: |
        nix build "github:NixOS/nix?rev=1ec4efa6c82fb6d90887c21aa7c7c6f3c644dd65" -o nix
        PATH="$PWD/nix/bin/:$PATH"
        export PATH
        echo "PATH=${PATH}" >> $GITHUB_ENV
        nix --version
        nix build
        mkdir build
        cp -RL ./result/* ./build/

    - name: Deploy to Netlify
      uses: nwtgck/actions-netlify@v1.1
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      with:
        production-branch: 'main'
        production-deploy: false
        publish-dir: './build'
        github-token: ${{ secrets.GITHUB_TOKEN }}
        deploy-message: 'Deploy from GitHub Actions'
        enable-pull-request-comment: true
        enable-commit-comment: true
        enable-commit-status: true
        overwrites-pull-request-comment: false
      if: github.repository == 'NixOS/nixos-summer'
